### ISSUE TITLE
interrogating RT Structures

### ISSUE THREAD

**Issue by mcjury** [SlicerRt/SlicerRT#123]
I want to do something quite simple.
I want to interrogate some RT images & their RT structures - get the intensity values of voxels in the structures; perhaps generate some histograms of the voxels in the structures.

Now, most software which will let me load up RT images and the assoc. structures, won't easily let me get the raw voxel intensity values - they are only interested in giving doses and volumes.

Will Slicer/SlicerRT let me get voxel intensity values for RT structures???

Thanks
mark

**Comment by cpinter** [comment]
Yes, it is possible. Install a recent Slicer nightly, then install SlicerRT from the Extension Manager. Import your DICOM studies in the DICOM browser, then load them. You will be able to see the loaded items in the Data module. The RT images are volume nodes, and the RT structure is a segmentation node, which is much more complex than a volume node, so you need to get its binary labelmap representation to be able to programmatically manage its voxels.

All the details for the steps I mentioned are available on the [Slicer wiki](https://www.slicer.org/wiki/Documentation/Nightly) and the [Slicer forum](https://discourse.slicer.org/). If you have more questions about any of the steps, then please post on the forum, so that more people can benefit from the answers you get (please also link to this ticket).

**Comment by cpinter** [comment]
Since there has been on activity about this question for three weeks, I'm closing this issue. Please reopen if you'd like to resume the discussion.
