### ISSUE TITLE
Extension tests failing due to missing LandmarkRegistration dependency

### ISSUE THREAD

**Issue by jamesobutler** [SlicerRt/SlicerRT#140]
Tests have been failing in the same way for SlicerRT since February 21st due to RegistrationLib being unable to be imported as this comes from [LandmarkRegistration](https://github.com/Slicer/LandmarkRegistration) which was turned off completely in Slicer in https://github.com/Slicer/Slicer/commit/4daabe1342cdc01ebe516da96ee9547aac243156.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Volumes/Dashboards/Preview/Slicer-0-build/python-install/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/Dashboards/Preview/S-0-E-b/SlicerRT-build/inner-build/lib/Slicer-4.11/qt-scripted-modules/PlmRegister.py", line 4, in <module>
    import RegistrationLib
ModuleNotFoundError: No module named 'RegistrationLib'
loadSourceAsModule - Failed to load file "/Volumes/Dashboards/Preview/S-0-E-b/SlicerRT-build/inner-build/lib/Slicer-4.11/qt-scripted-modules/PlmRegister.py"  as module "PlmRegister" !
Fail to instantiate module  "PlmRegister"
```

**Comment by Sunderlandkyl** [comment]
Thanks for bringing this up! Do you know if anyone has taken on the task of updating the LandmarkRegistration module so that it can be re-enabled?

**Comment by jamesobutler** [comment]
Andras assigned https://github.com/Slicer/Slicer/issues/4764#event-3166405202 himself to a Slicer issue about updating LandmarkRegistration so that it could be enabled again in Slicer, but it doesn’t have the “in progress” status label so I don’t believe work has started yet.

**Comment by lassoan** [comment]
@Sunderlandkyl you are very familiar with Markups now. Could you take a stab on fixing the module?

I wanted to rework it a bit to make it more flexible, convenient, and robust - it would be nice to address some of these as well:
- allow placing landmarks separately, because right now if you place a landmark on an image then it automatically places it on the other, too, which is really bad if the two images are initially not aligned well
- do not force setting input volumes when entering the module: the popup annoys me a lot and prevents you from using the module for model-to-model, model-to-image, etc. segmentations
- markups are not associated with the parameter node robustly (it should use node references)

**Comment by Sunderlandkyl** [comment]
@lassoan sure, sounds good!

**Comment by jamesobutler** [comment]
LandmarkRegistration was added back into Slicer with https://github.com/Slicer/Slicer/commit/3987c758f59e5cc70b645d05d4db890e8b0202d1 so the tests aren't failing in this manner now.
