### ISSUE TITLE
Is Registration necessary to run ExternalBeamPlanning?

### ISSUE THREAD

**Issue by MarcoSerna** [SlicerRt/SlicerRT#97]
I've written about this issue previously, but had a follow up question (Issue #95). For some reason, I get an Internal error when trying to run Plastomatch Proton Dose Engine if I do not run a General Registration of the Dicom image set with itself. Did you experience this issue? Here are photos for reference.
![image_registration](https://user-images.githubusercontent.com/16005832/49891705-00b13700-fdfc-11e8-8e6c-42252ec018ec.PNG)

**Comment by cpinter** [comment]
Is the internal error the same as in the issue you referenced?

The error suggests that the image scalar type (double) is not supported by Plastimatch. Your registration workaround works because the output image will be of a different scalar type.
You can do the same cast in the module that exists for this purpose: Cast Scalar Volume. What you need to do is select Short as output type and click Apply. It's more deterministic and faster too.

I'll let @gregsharp react to the original error message and the inability to handle double volumes.

**Comment by MarcoSerna** [comment]
Thank you for a quick response! It worked like a charm, thank you again.

**Comment by gregsharp** [comment]
Thank you Marco for the report.  This should now be fixed.  -Greg

**Comment by cpinter** [comment]
As the cause of the issue is fixed as well, I'm closing the ticket.
